gcc-{runtime,sanitizers}-external: fix removal of dep upon gcc-source
Without this, we get this failure when using an external toolchain:

    ERROR: Nothing PROVIDES 'gcc-source-11.3.0-13.0.1'. Close matches:
    gcc-source-11.3.0

Signed-off-by: Christopher Larson <chris_larson@mentor.com>